### ISSUE TITLE
Scraper-Tool Liste

### ISSUE THREAD

**Issue by FlxVctr** [Leibniz-HBI/Social-Media-Observatory#1]

**Comment by manilevian** [comment]
Liebe Kollegen,

momentan erarbeite ich eine Liste mit funktionierenden Tools die behilflich sein können, Informationen von Social Media- und Nachrichtenplattformen  zu scrapen.  
Diese Liste ist momentan noch ein Google Sheet

**EDIT:** Da es sich um eine Liste von Open Source Programmen handelt, kann ich die Liste gerne öffentlich teilen.  Hier gehts zur [Scraper Liste](https://docs.google.com/spreadsheets/d/1uYEmUz7PNUclgrVWC_sLE1QQKhm6flozFHDg5Mt_bCs/edit?usp=sharing)


Die Liste wird in den kommenden Wochen auch in das Wiki auf Github aufgenommen, sobald das Konzept dafür erarbeitet worden ist.

Mit den besten Grüßen,

Mani

**Comment by FlxVctr** [comment]
https://www.dropbox.com/s/tot9joj6axht2g3/Instagram%20workshop%20-%20AoIR2019.pdf?dl=0 

@manilevian : Kannst du das mal ansehen und in die Instagram-Scraper Liste integrieren. Danke :)

**Comment by FlxVctr** [comment]
Auch vielleicht ein paar interessante Kategorien in der Tabelle drin.

**Comment by manilevian** [comment]
Hi Felix,

vielen dank für die Präsi. Sehr hilfreiche Liste, vor allem weil ich API basierte noch garnicht integriert habe. Werde die Liste genau anschauen und unsere daraufhin editieren. 

Lg.

**Comment by manilevian** [comment]
I will close this Issue, since it is being resolved within [the merged Scraper List Issue](https://github.com/Leibniz-HBI/Social-Media-Observatory/issues/10).
