### ISSUE TITLE
Merge API and scraper tool list in Wiki for end users

### ISSUE THREAD

**Issue by FlxVctr** [Leibniz-HBI/Social-Media-Observatory#10]
After completion of #1 and #2 we should merge the results in a user-friendly list/table in the Wiki or a Google Spreadsheet linked/embedded in the Wiki. This list should especially exclude untested/not fully working tools and provide a good first comparison of tools sorted by platforms. Later this will be linked to more detailed descriptions and HOW TOs.

**Comment by manilevian** [comment]
Jason and I have created [a merged Spreadsheet](https://docs.google.com/spreadsheets/d/1vZ6jOWoxcyockeNMDE5wbEcx_kSoSmkIqJ8olKyJfq0/edit?usp=sharing) to merge both of our Lists into one. We are working on the completion of the lists and will be embedding pictures or a Markdown tables within the Wiki pages on github. 

You can check process here. Feel free to post any categories we might have missed and I will edit the Spreadsheet asap.

**Comment by young-jason** [comment]
Final API Tool-List was [archived](https://docs.google.com/spreadsheets/d/1i-sEVAcIrZg4dVrkSsFTD-Ct0hpP2mP3uaSmN9iND5E/edit#gid=1462513788) and [merged](https://docs.google.com/spreadsheets/d/1vZ6jOWoxcyockeNMDE5wbEcx_kSoSmkIqJ8olKyJfq0/edit#gid=0) with the Scraper Tool List. All reviewed and recommendable API-Tools were inserted into the [Tools Section](https://github.com/Leibniz-HBI/Social-Media-Observatory/wiki/Tools) of our Wiki.

**Comment by FlxVctr** [comment]
@manilevian can this issue be closed?
