### ISSUE TITLE
Workshop Concept Results

### ISSUE THREAD

**Issue by manilevian** [Leibniz-HBI/Social-Media-Observatory#11]
Hi,

Here is the document, containing all the brainstorming from the SMO-Workshop. 

best regards,

Mani

[Results SMO Workshop](https://github.com/Leibniz-HBI/Social-Media-Observatory/files/3728892/SMO_Workshop_16-17.09.2019_Kartchen.docx)

**Comment by FlxVctr** [comment]
Should be implemented as issues as we go.
