### ISSUE TITLE
Update Home Page with description of sections

### ISSUE THREAD

**Issue by FlxVctr** [Leibniz-HBI/Social-Media-Observatory#14]
Maybe move instructions how to edit the wiki somewhere else. However, leaving them on the homepage would lower the barrier for participation in editing the Wiki.

**Comment by manilevian** [comment]
I added a [How to maintain and use this wiki](https://github.com/Leibniz-HBI/Social-Media-Observatory/wiki/How-to-use-and-maintain-the-wiki) Page to the Tutorial Section of the wiki. I havent changed the first page though. 
However, I havent changed anything on the Homepage of the Wiki. We need to (maybe) add a simple short description of the Wiki (Why, what and where) and ofc. how you can participate to the wiki. I couldn’t think of more I would put on the starting page.

**Comment by FlxVctr** [comment]
I agree, we should rather have a summary of the main sections (Tools, Tutorials, Ethics) and their purpose on the home page.

**Comment by FlxVctr** [comment]
@manilevian I did something. Please have a look and close issue or comment.

https://github.com/Leibniz-HBI/Social-Media-Observatory/wiki

**Comment by manilevian** [comment]
@FlxVctr looks really good. Thats exactly what I was thinking about. We can simply add the rest whenever we have the content.
