### ISSUE TITLE
Add/Switch instagram-scraper

### ISSUE THREAD

**Issue by FlxVctr** [Leibniz-HBI/Social-Media-Observatory#17]
https://github.com/rarcega/instagram-scraper

**Comment by manilevian** [comment]
changed it within the "merged scraper list" and changed the Link within our Wiki. Also the Table has been updated.

I have also rechecked all the apps :)!

**Comment by FlxVctr** [comment]
Link is not updated
Picture/table should show that user info is also available via instagram scraper

**Comment by FlxVctr** [comment]
Also, description should include (actually for every tool) whether posts can be searched for by location, hashtags, and users.

**Comment by manilevian** [comment]
Thanks for checking!
I changed the table accordingly and added User Info to the IG-S. 
I also added location/user to the description. I will reevaluate the location/Usr search in the following days for ALL Apps and edit the other descriptions.

**Comment by FlxVctr** [comment]
Made an issue for that: #20
