### ISSUE TITLE
API-Tool Liste

### ISSUE THREAD

**Issue by FlxVctr** [Leibniz-HBI/Social-Media-Observatory#2]
Sammlung an zu testenden Tools zur Sammlung von Social Media Daten via APIs.

(Assigned: Jason)

**Comment by young-jason** [comment]
Die aktuelle Liste findet sich hier: [Tools zur Sammlung von Social Media Daten via APIs](https://docs.google.com/spreadsheets/d/1i-sEVAcIrZg4dVrkSsFTD-Ct0hpP2mP3uaSmN9iND5E/edit?usp=sharing)

Es handelt sich um eine erste Auflistung, die laufenden Änderungen unterliegt. Das Ziel ist, die Tools zu testen und eine kurze Rezension/Empfehlung zu jedem Tool zu verfassen. Die Design-Philosophie lautet: Getestete Qualität und subjektive Empfehlung vor Vollständigkeit. Die Liste wird in den kommenden Wochen auch in das Github-Wiki aufgenommen, sobald das Konzept dafür erarbeitet worden ist.

**Comment by young-jason** [comment]
Final API Tool-List was [archived](https://docs.google.com/spreadsheets/d/1i-sEVAcIrZg4dVrkSsFTD-Ct0hpP2mP3uaSmN9iND5E/edit#gid=1462513788) and [merged](https://docs.google.com/spreadsheets/d/1vZ6jOWoxcyockeNMDE5wbEcx_kSoSmkIqJ8olKyJfq0/edit#gid=0) with the Scraper Tool List.
