### ISSUE TITLE
Scrape Modules!

### ISSUE THREAD

**Issue by manilevian** [Leibniz-HBI/Social-Media-Observatory#21]
Hey,

I could add the Modules under every Social Media Tool site. 
Alternatively, I could make a Scrape Modules Site, for more advanced researchers and simply link all Social Networks Modules in one page. ofc. with descriptions and more.

The argument for a new site is, that we would not overload the toollist and keep it simple. On the other hand, less sites are more lucid. 

Whats your opinion :)?

**Comment by FlxVctr** [comment]
I'd put them at the bottom of the existing pages with a clear hint that this is for advanced users only.

>
>
