### ISSUE TITLE
Collect ethic guidelines for research involving (social) media data

### ISSUE THREAD

**Issue by FlxVctr** [Leibniz-HBI/Social-Media-Observatory#23]
https://aoir.org/ethics/ for example

**Comment by FlxVctr** [comment]
RatSWD [Rat für Sozial- und Wirtschaftsdaten] (2019): Big Data in den Sozial-, Verhaltens- und Wirtschaftswissenschaften: Datenzugang und Forschungsdatenmanagement. RatSWD Output 4 (6). Berlin, Rat für Sozial- und Wirtschaftsdaten (RatSWD). https://doi.org/10.17620/02671.39

**Comment by FlxVctr** [comment]
DGPuK: https://www.dgpuk.de/sites/default/files/fachgruppen/AG_Forschungsdaten%20Empfehlungen%20DGPuK.pdf

**Comment by stephandreyer** [comment]
Fraunhofer IOSB (2019), GUIDEline - Leitlinien für den Datenschutz in der wissenschaftlichen Forschung zu Aspekten der Mensch-Technik-Interaktion, https://www.iosb.fraunhofer.de/servlet/is/77819/GUIDELine.pdf

**Comment by FlxVctr** [comment]
Oxford Research Support: https://researchsupport.admin.ox.ac.uk/policy/data 
[data_protection_and_research.pdf](https://github.com/Leibniz-HBI/Social-Media-Observatory/files/4170365/data_protection_and_research.pdf)
