### ISSUE TITLE
Test and add Facepager to Facebook Tools

### ISSUE THREAD

**Issue by FlxVctr** [Leibniz-HBI/Social-Media-Observatory#24]
https://twitter.com/jajuenger/status/1207024036032786432?s=20

**Comment by manilevian** [comment]
This app is actually on my "Check later for improvements" list :D! He finally got approved which is pretty cool. Before the API wrapping kept failing and therefore it didnt make the List. I will work through the app in the following week. I am still in the mids of the Instagram tests.

**Comment by manilevian** [comment]
I worked through the App and it amazingly works for Twitter, Youtube and Facebook. The documentation is very good too, it has a GUI running on Linux,Mac and Win, which makes it the very first GUI program we have :). I am still not done with the ocumentation, but I will add it to our list. I

**Comment by FlxVctr** [comment]
Great, thank you!
