### ISSUE TITLE
Twitter-Scraper

### ISSUE THREAD

**Issue by FlxVctr** [Leibniz-HBI/Social-Media-Observatory#27]
> Hey, guckt euch mal diesen Thread an:
> https://twitter.com/BrendanNyhan/status/1214215312863875072?s=20
> und speziell die Hinweise auf twint/twitterscraper
> 

via email

**Comment by manilevian** [comment]
Looks very interesting and promising: https://github.com/twintproject/twint
Added it to out merged scraper list on gmail to evaluate the possibilities later

**Comment by manilevian** [comment]
Twint was already in the list (I remember Jason talking about it) and I added the twitterscraper to it too. I'll close the ticket for now  and evaluate the Twitterscraper.
