### ISSUE TITLE
Check Heidelberg Cloud

### ISSUE THREAD

**Issue by janhinrikschmidt** [Leibniz-HBI/Social-Media-Observatory#29]
https://heicloud.uni-heidelberg.de/heiCLOUD

könnte evtl. für unsere Infrastruktur in Frage kommen (Sebastian hat da nähere Infos bzw. auf dem Zettel, dort mal Projekte "auszulagern"

**Comment by manilevian** [comment]
Klingt auf dem ersten Blick tatsächlich sehr entspannt. Wissen wir wieviel die Kosten genau aussehen würden? Falls nicht kann ich den Damen und Herren gerne eine Anfrage schicken, hierfür bräuchte ich lediglich folgende Infos: 

- Projektname (nur intern):
- Projektbeschreibung (nur intern):
- Anzahl vCPUs:
- RAM in GB:
- HDD in GB:
- Anzahl öffentlicher IPv4 Adressen:

Ich habe leider noch kein Beispiel, indem wir sowas brauchten. @FlxVctr hast du ggf. einmal Mindestanforderungen an Server für scraping Aufgaben? 

Lieben Gruß!

**Comment by FlxVctr** [comment]
Gerade haben wir t2.medium bei AWS (mit nem 256GB Volume): https://aws.amazon.com/ec2/instance-types/

Das sind 2 cores (ca bis zu 3GHz) und 4GB RAM.

Es wäre allerdings gut, noch mehr cores und RAM flexibel zur Aufteilung auf weitere Instanzen zur Verfügung zu haben. Hängt davon ab, wie schnell sowas dann genehmigt wird, ob wir das gleich beantragen würden oder erst bei Bedarf.

Ich würde allerdings mit einem Antrag warten, bis wir die Landing Page haben und wirklichen konkreten Bedarf. Gerade sammeln wir ja nichts.

**Comment by manilevian** [comment]
Ich wollte erstmal preise zwischen den Anbietern vergleichen. Nix offizielles ;)

**Comment by manilevian** [comment]
I'll link this to Issue #49 and close this one :)!
