### ISSUE TITLE
Landing Page

### ISSUE THREAD

**Issue by FlxVctr** [Leibniz-HBI/Social-Media-Observatory#3]
Lay-understandable landing-page with

- Mission Statement
- Short concept of the SMO
- Links to all parts of the SMO that are at least in a 'public beta' stage

Realisation should be easy via github pages (https://pages.github.com/) and either Jekyll or Hugo (and academic theme: https://sourcethemes.com/academic/)

**Comment by manilevian** [comment]
My friend just send me this site: https://startbootstrap.com/
Contains loads of templates in huge, jekyll and others. 
Thought i'll share ;)

**Comment by manilevian** [comment]
Quickly summarizing what happened in the meanwhile :)! 

- We added a repo for out landing page on GitHub, which you can access [over here ](https://github.com/Leibniz-HBI/SMO)
- We added the necessary pages and redirects to the site
- The site is now accessible over the following link: https://leibniz-hbi.github.io/SMO/

I will close this Issue on this repo. If you have any issues considering the landing page of our project please [open an Issue on the repo of the Landing page](https://github.com/Leibniz-HBI/SMO/issues)
