### ISSUE TITLE
Work through list to complete community standards

### ISSUE THREAD

**Issue by FlxVctr** [Leibniz-HBI/Social-Media-Observatory#34]
https://github.com/Leibniz-HBI/Social-Media-Observatory/community

Especially the Code of Conduct, Contribution Guidelines and the License should be completed.

**Comment by manilevian** [comment]
Do we want to write a own one or can we use a template. Seen a couple which could be used for us too.

**Comment by FlxVctr** [comment]
Re CoC I like and already have used this one as a template: https://www.contributor-covenant.org/ 

Also for the other stuff I'd base everything on existing guidelines.
