### ISSUE TITLE
Collect news scrapers

### ISSUE THREAD

**Issue by FlxVctr** [Leibniz-HBI/Social-Media-Observatory#37]
https://github.com/fhamborg/news-please

**Comment by manilevian** [comment]
Hey, we have a whole list of News Scrapers in our Merged Scraper List on Google. We simply havent added them to the wiki yet. 

Here the Link to the [Scraper List](https://docs.google.com/spreadsheets/d/1vZ6jOWoxcyockeNMDE5wbEcx_kSoSmkIqJ8olKyJfq0/edit?usp=sharing)

Also News Please is in there! You can find the table under the name "General Scrapers"

**Comment by FlxVctr** [comment]
@manilevian Ok, I'd put the link to the Google Doc also in the Wiki (maybe below the table on each page)

**Comment by manilevian** [comment]
I added a little note to the end of the Ig- and twitter tools site. If the sentence is okay like that, i'd add it to the upcoming tool sites too. Just give me your go :D

**Comment by FlxVctr** [comment]
I'd cut the justification for why we left out some tools and just say something along the lines that if people want to check out/comment on our working document they can do it there.
