### ISSUE TITLE
Evaluate Wiki solutions

### ISSUE THREAD

**Issue by FlxVctr** [Leibniz-HBI/Social-Media-Observatory#4]
Assigned to Jason

**Comment by young-jason** [comment]
Das aktuelle Memo findet sich hier:[ Memo FGZ Wiki](https://docs.google.com/document/d/1fJ255bJWC7ts4xxSllOv2vTF1ctzzTSdoKaC4bUHH6c/edit?usp=sharing)
Die offenen Fragen werden weiterhin bearbeitet, damit wir nach Felix' Rückkehr eine abschliessende Diskussion durchführen können.

**Comment by young-jason** [comment]
Die Analyse zur Errichtung eines Wikis im Rahmen des FGZ hat ergeben, dass das Wiki vorerst auf Englisch in GitHub geführt werden soll. Github bietet den grossen Vorteil eines all-in-one-tools (Projektmanagement, Code hosting und Wiki). Außerdem ist die Bearbeitung in Markdown sehr einfach und die Wiki-Artikel können bei Bedarf einfach als Textfiles exportiert werden. Sollte im Verlauf der Zeit eine andere Lösung bevorzugt werden, könnte Sebastian Schieke (IT) ein WordPress-Wiki analog zur Mutter aufsetzen, welches mit den exportierten Textfiles in kurzer Zeit einsatzbereit wäre. Das entsprechende [Dokumentationsmemo](https://docs.google.com/document/d/1fJ255bJWC7ts4xxSllOv2vTF1ctzzTSdoKaC4bUHH6c/edit?usp=sharing) ist auf dem HBI-Server abgelegt.
