### ISSUE TITLE
finalise first version of Twitter data collection tools in wiki

### ISSUE THREAD

**Issue by FlxVctr** [Leibniz-HBI/Social-Media-Observatory#41]
At least with the tools we already have in the Google Spreadsheet. Template is the Instagram tools wiki page.

**Comment by manilevian** [comment]
While doing this, I was thinking about the SMO-TMAS app that Jason did during his time in the institute. Would you add the application to the List or would you say, it's basically not that important. It doesn't do anything that is groundbreaking towards the other apps. Therefore my thoughts were cutting it from the list. Also I don't know if Jason will have the time to maintain it over the next years. 

Whats your thought?

**Comment by FlxVctr** [comment]
I'd leave it in, also because it's a nice example how to create a shiny app (which is a good topic for the how to section). (On a side note: Before, we were thinking to exclude R apps, but I think we should rethink that. It's too popular in the community and we can actually build up the competence to give some support.)

But make sure to include the stuff by [VOSON Lab](http://vosonlab.net/) as well, as it is very similar but more powerful.

**Comment by manilevian** [comment]
Ohrighty, I added VSON back to the list. 
Also I will keep the TMAS app within the list!

**Comment by manilevian** [comment]
First version is online and ready to check! I used the same wording as for the IG Tools. Hope its okay like that.

**Comment by FlxVctr** [comment]
* Installation via <--> Installation trough. Choose one.
* Notable Features: Some of them are notable limitations (cf. Instagram tools)
* Twint is not API based according to the description, but API based according to the table
* Installation via/trough:
    * pip3 is pip.
    * Facepager: I assume you mean they have installation packages for these platforms, please clarify
* TAGS: Documentation links to forum, not to documentation, please check links for other platforms again as well
* Voson stuff: I actually meant that if we list our Shiny App, we should list Voson Dashboard as well: http://vosonlab.net/tools Maybe also some of the other tools
* Browser-based tools: installation via is missing: are they hosted? Or do I have to install them?

Also made some edits right away (https://github.com/Leibniz-HBI/Social-Media-Observatory/wiki/Twitter-Tools/_compare/ef4161396b74561248bca12d1257d4b3096262ca...57f1ae531ccc6dce24427ac0db878fdb9f7073fb )

**Comment by manilevian** [comment]
Thanks a lot!

- Changed all to "Installation via" 

- Added limitations if there are any!

- Changed the Table and edited twint to non api

- changed all to pip

- Installation via for Hydrator and Facepager have been clarified (I guess)

- VosonDash has been added, SML therefore removed. I have only had a day of testing the app, so i am sorry if its a bit "Slick". I will hopefully find time testing it in depth. 

- Browser based tools (TAGS) now have an installation guid!

- I added the support forum of TAGS to the sheet. 

- Added "No local installation needed" to SMO-TMAS application to point out that it does not need any installation whatsoever. 

- Looked through all "documentation links" etc. and have edited some of them to more direct resources. 

Hope that does it :)

**Comment by FlxVctr** [comment]
Some minor things that caught my eye:

1.

> Most of these Twitter tools connect to official Twitter APIs and therefore need an API Key from Twitter. You can retrieve an API key from Twitter easily, just follow the documentation. You are bound to the restrictions given by Twitter. You can read about these here.

The link behind here is not very specific.

2. I think we should specify what a tool can collect, maybe in its description, if we have only 'partially' in the table. What do you think?

**Comment by FlxVctr** [comment]
So, for example, for twarc, I'd be interested what information it doesn't collect for location.

**Comment by manilevian** [comment]
I will add this link to the direct rate limits: https://developer.twitter.com/en/docs/basics/rate-limits 

In fact, twarc can search for locations and also pull the needed information for a tweets location, if it is a non priv. information. Therefore the table is wrong. 

The only Application that would need a new information therefore is our SMO-TMAS. Since its a visual application i am not sure if you really need to describe it since you can see whats being fetched after one click. Ofc. I can add it if you like too. 

I will check through the table again, since this is the second mistake.

**Comment by FlxVctr** [comment]
Cool, thanks :) Let me know when you're done.

**Comment by manilevian** [comment]
Changed the table, added "No local installation needed" to SMO-TMAS!

I checked through the table, and all features should be marked correctly. The features have been checked again and all are defined or noted as limitation. The links to all documentations have been checked, please ensure if the documentation links for VSON are okay now, since they only have a forum, it wasnt so easy to find :)!

**Comment by FlxVctr** [comment]
Looks good! Closing this for now. Thanks for your work 👍
