### ISSUE TITLE
Check out Twitter Explorer

### ISSUE THREAD

**Issue by FlxVctr** [Leibniz-HBI/Social-Media-Observatory#46]
https://arxiv.org/pdf/2003.03599.pdf

We present an open-source interface for scientists to explore Twitter datathrough interactive network visualizations. Combining data collection, trans-formation and visualization in one easily accessible framework, thetwitterexplorerconnects distant and close reading of Twitter data through theinteractive exploration of interaction networks and semantic networks. Bylowering the technological barriers of data-driven research it aims to at-tract researchers from various disciplinary backgrounds and facilitates newperspectives in the thriving field of computational social science

**Comment by manilevian** [comment]
https://github.com/pournaki/twitter-explorer

here the link to the application. It sounds pretty promising and easy to use, ill test through it today/tommorrow and add it to our list.
