### ISSUE TITLE
Find/Write script that converts the wiki markdown into a jekyll site

### ISSUE THREAD

**Issue by FlxVctr** [Leibniz-HBI/Social-Media-Observatory#52]
There are some scripts out there but some of them are pretty old.

Goal is to be able with one command to:

* clone/pull the wiki markdown files
* generate the necessary files for a jekyll site
* place them into a simple jekyll template
* push the whole thing to a repo which creates a pretty version of the wiki

**Comment by Khandoker09** [comment]
I have cloned markdown file and generated jekyll template . 
the template might need to edit to get more professional look.
you can find it under "leiniz-HBI/SMO-wiki" repo 
and the jekyll template is under this link.
https://leibniz-hbi.github.io/SMO-Wiki/

**Comment by FlxVctr** [comment]
I think we can work with that. Some adjustments to colour etc.

Does the sidebar support a nested layout?

**Comment by Khandoker09** [comment]
sidebar does not allow nested layout yet. but i can edit the sidebar by editing the css file. Maybe also have to add the search option .

**Comment by FlxVctr** [comment]
At some point, can you give us a quick write-down/flow-diagram with a rough concept, how to automate the import from the wiki, so that we can discuss that?
