### ISSUE TITLE
Add Grafana and Tableau to Statistics Analysis Tools list

### ISSUE THREAD

**Issue by FlxVctr** [Leibniz-HBI/Social-Media-Observatory#55]

**Comment by manilevian** [comment]
Well we didn’t have a list yet but i guess its time to make one:

[Here it is](https://docs.google.com/spreadsheets/d/1lHQxgzh9zGnn-tb8UPpPppIjZO1Env0qho6rdfYrnMc/edit?usp=sharing)

here it is. I also added another 2 names. I haven’t really thought about any categories to sort them. I added some, but i think we will have to reevaluate those. I also think we cannot handle thinks the way we did for the wikis we did until now. Maybe less categories, more explanation. The plus is, most of the tools have RICH documentations. Not like smaller Scrape Projects :)!
The list is ofc. not done yet and if you find anything interessting just post it. Ill evaluate and add them later.

**Comment by FlxVctr** [comment]
Because these tools will get pretty complex I'd just have a pro and con list so far.

Category-wise I like the categories we have in the wiki so far (Network Analysis, Content Analysis, Statistics (which would be the right one for Tableau and Grafana)), but that might change.

**Comment by FlxVctr** [comment]
Pro and Con List as well as a three sentence purpose summary ofc.
