### ISSUE TITLE
Pluragraph API evaluieren

### ISSUE THREAD

**Issue by FlxVctr** [Leibniz-HBI/Social-Media-Observatory#6]
https://pages.pluragraph.de/api/

evtl. DBÖS in MySQL o.Ä. einpflegen und mit Pluragraph synchronisieren

**Comment by janhinrikschmidt** [comment]
Kurz zur Info/Background: Wir haben über Martin Fuchs vor einigen Jahren eine ganze Reihe von Datensätzen aus Pluragraph bekommen, um die DBÖS initial zu füllen. Der Kontakt bzw. die Möglichkeit besteht wohl weiterhin; wir können aber gerne mit ihm auch mal über andere Wege des Datenaustauschs sprechen. Bei Bedarf stelle ich den Kontakt her bzw. lade ihn mal zu uns ein.

**Comment by janhinrikschmidt** [comment]
.. und das Überführen von DBÖS in eine SQL-Datenbank ist Teil des schleppend verlaufenden Vorhabens mit dem externen Entwickler; die DBÖS mit einem Webinterface zur Eingabe/Export von Einträgen zu versehen. Definitiv ein issue für die weitere Planung, wie wir damit vorgehen :-)

**Comment by FlxVctr** [comment]
Einladen klingt gut! Zumindest das überführen in eine SQL-Datenbank sollte kein Problem für uns sein. Interface könnte man vielleicht mit Shiny basteln (womit Cornelius sich auskennt und Jason gerade mit befasst und ich auch noch lernen wollte).

**Comment by FlxVctr** [comment]
Will be its own project. Closing
