### ISSUE TITLE
add Twitter API 101 course by Twitter to Wiki

### ISSUE THREAD

**Issue by FlxVctr** [Leibniz-HBI/Social-Media-Observatory#89]
https://github.com/twitterdev/getting-started-with-the-twitter-api-v2-for-academic-research

Work/sift through the course, write a short summary (3 sentences) and add to https://smo-wiki.leibniz-hbi.de/Courses

**Comment by Khandoker09** [comment]
added, however, I have written the summary in  4 lines. I hope that's okay. ..

**Comment by FlxVctr** [comment]
Thanks, needed some work, pushed it to the website:
https://smo-wiki.leibniz-hbi.de/Courses
