### ISSUE TITLE
Add page with markdown editor 

### ISSUE THREAD

**Issue by Khandoker09** [Leibniz-HBI/Social-Media-Observatory#90]
find 
free multi platform  markdown editor

**Comment by Khandoker09** [comment]
https://docs.google.com/document/d/1paz72xQAYXDodpbmOccLpZNuMvMHqWEwcHo4cedF9Sk/edit?usp=sharing

**Comment by FlxVctr** [comment]
I added some comments. Please revise. Thank you!
